"""empty message

Revision ID: 45bf8b726dfc
Revises:
Create Date: 2025-06-18 12:59:51.312161

"""

# revision 파일이라고 부름.
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45bf8b726dfc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column(
            "completed", sa.Boolean(), server_default=sa.text("(false)"), nullable=True
        ),
        sa.Column(
            "important", sa.Boolean(), server_default=sa.text("(false)"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todo")
    # ### end Alembic commands ###
